<?php
//    $gamerTag = $_GET['gamerTag'];
//    $url = "https://api.clashofclans.com/v1/players/%23".urlencode($gamerTag);
//    $token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjkyMWQ1YzE5LTU4YmMtNDA4NS05ZTEyLTgwYmJkNDgyYWQxZiIsImlhdCI6MTU0OTk5MTA5Nywic3ViIjoiZGV2ZWxvcGVyLzA1YzdhZjJmLTE4NWEtM2EyYS1kYWY2LWVhZjA0YmY0NDhmMCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE3NC4xMTIuMTY3LjIxMiJdLCJ0eXBlIjoiY2xpZW50In1dfQ.Xh3fbN7P4iAowts5YgkgRqXnH-DLpL2p5OotvwLiPSymywvDX_sY-m00gGx0v4OQkSsxJKDQ1HAVKIYO6SlIkw";
//
//    $ch = curl_init($url);
//    $header = array();
//    $header[] = "Accept: application/json";
//    $header[] = "Authorization: Bearer ".$token;
//
//    curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
//    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
//    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
//    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
//
//    $res = curl_exec($ch);
//    echo $res;
echo 'Hello';
?>